### ISSUE TITLE
关于不同线束激光雷达！

### ISSUE THREAD

**Issue by Karkers** [xueking1/kitti_distance_eval#1]
您好，我想知道您是否知道如何对不同线束的激光雷达进行结果分析！！！

**Comment by xueking1** [comment]
您好，没能及时回复您。目前我仅测试了基于KITTI（64 lines）的不同距离下的检测精度，而对于Waymo（64 lines），nuScenes（32 lines）并没有来得及测试。同时，网上有很多从64线中抽取32、16线的代码，您可以尝试进行测试评估，或许有新的发现！谢谢！

**Comment by Karkers** [comment]
感谢您的回复，我想知道为什么0-10m的检测精度很低和论文中0-15m的有很大差异

**Comment by xueking1** [comment]
> 感谢您的回复，我想知道为什么0-10m的检测精度很低和论文中0-15m的有很大差异
您好，我猜测这个问题和模型设计有着很大的关系，您可以尝试分别消融掉VirConv中某个模块（例如StVD，NRConv and so on），去测试哪个模块对于这一部分有较大的提升。

当然，我自己曾经也尝试添加了能够提升远距离检测的模块（远距离形状补全），最终结果显示0-10，10-20，20-30，30-40m检测范围内的精度提升都较为平缓，但是在40-inf检测范围内的精度却获得了较大的提升，因此我认为通过消融实验或许您能够得到相应的答案。

**Comment by xueking1** [comment]
> 感谢您的回复，我想知道为什么0-10m的检测精度很低和论文中0-15m的有很大差异

您好，感谢您提出的问题。我猜测这个问题和模型设计有着很大的关系，您可以尝试分别消融掉VirConv中某个模块（例如StVD，NRConv and so on），去测试哪个模块对于这一部分有较大的提升。

当然，我自己曾经也尝试添加了能够提升远距离检测的模块（远距离形状补全），最终结果显示0-10，10-20，20-30，30-40m检测范围内的精度提升都较为平缓，但是在40-inf检测范围内的精度却获得了较大的提升，因此我认为通过消融实验或许您能够得到相应的答案。期待您能顺利解决该问题，谢谢！

**Comment by xueking1** [comment]
> 感谢您的回复，我想知道为什么0-10m的检测精度很低和论文中0-15m的有很大差异

抱歉，我之前误解了您的意思，现在我似乎理解了您的疑惑。在VirConv的图7中，作者测试的是相比于baseline的提升，而非直接展示VirConv在不同距离下的检测精度。您可以测试一下作者使用的baseline以及VirConv在不同距离下的检测精度，并且计算一下两者之间的差距看是否符合图中的描述，谢谢！
